# Generated by Django 4.2.1 on 2023-05-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user1',
            new_name='participant1',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='user2',
            new_name='participant2',
        ),
    ]
