# Generated by Django 4.2.1 on 2023-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='testRoom', max_length=100),
        ),
    ]
