# Generated by Django 4.2.1 on 2023-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_rename_user1_chatroom_participant1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processed_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
